// Foundation Phase 1 — Batch F4 — Unified Execution Context.
// Shapes mirror the real GET /api/journey-state response
// (src/app/api/journey-state/route.ts) plus client-derived state that
// route does not compute (status, entity selection, event timeline).

export type ExecutionEntityType = 'stage' | 'agent';

export interface ExecutionEntity {
  id: string;
  type: ExecutionEntityType;
  label: string;
}

export type StageStatus = 'pending' | 'active' | 'completed';

// Field-for-field match with JourneyStageOut in journey-state/route.ts,
// plus `id` and a client-derived `status`.
export interface StageState {
  id: string;
  status: StageStatus;
  summary?: string;
  decision?: string;
  reasoning?: string;
  confidence?: string;
  conflicts?: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  outputFile?: string;
  artifacts?: string[];
}

// agentsByStage in the API response is a list of agent-name strings
// (parsed from each artifact's "## Generated By" section) — no per-agent
// timing or status is persisted, so AgentState only models what's real.
export interface AgentState {
  id: string;
  stageId: string;
  status: 'completed';
}

export interface MetricSnapshot {
  currentStage: number;
  totalStages: number;
  completedStages: number;
  totalDurationMs: number;
  lastUpdated: string;
}

export interface RuntimeEvent {
  id: string;
  stageId: string;
  type: 'stage-started' | 'stage-completed';
  timestamp: string;
}

export interface JourneyStateResponse {
  currentStage: number;
  stages: Record<string, {
    summary?: string;
    decision?: string;
    reasoning?: string;
    confidence?: string;
    conflicts?: string;
    startedAt?: string;
    completedAt?: string;
    durationMs?: number;
    outputFile?: string;
    artifacts?: string[];
  }>;
  agentsByStage: Record<string, string[]>;
}
