'use client';

// src/components/workspace/ArtifactTree.tsx
// Sprint 07 (W1 + W2 + W3 partial) — dynamic artifact tree.
//
// Renders exactly one row per entry in `artifacts` — never a fixed count
// (Phase A/A1: artifacts is a dynamic fs.readdirSync() result). No stage
// slots are invented for files that don't exist on disk.
//
// Row state is derived per-artifact from its own stage number vs. currentStage:
//   Written  — stageNum < currentStage  → filled icon, full-brightness label, v{n}, chevron
//   Current  — stageNum === currentStage → ring/accent icon, weight up, chevron, auto-expanded
//   Pending  — stageNum > currentStage  → hollow icon, recessive label, v0, NO CHEVRON
// Pending only occurs if a file exists ahead of the recorded currentStage (rare,
// e.g. journey.json lagging a fast write) — never a synthetic row for a stage
// with no file.

import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ChevronRight, FileText, TriangleAlert,
  Target, Globe, Shield, CheckSquare, User, Map, AlertTriangle,
  Swords, TrendingUp, Boxes, ListChecks, BarChart3, Bot,
  type LucideIcon,
} from 'lucide-react';
import { parseContentDetailed } from '@/lib/parseContent';
import { parseSections, Section } from '@/lib/parseSections';
import { stageNum, stageColor, humanName } from '@/lib/artifactDisplay';
import { workspaceMotion } from './motion';

type RowState = 'written' | 'current' | 'pending';

function rowState(file: string, currentStage: number): RowState {
  const n = stageNum(file);
  if (n < currentStage) return 'written';
  if (n === currentStage) return 'current';
  return 'pending';
}

// Part 2 D3 — section heading keyword -> icon, case-insensitive, first match
// wins, FileText as fallback. No shared icon registry exists anywhere in the
// codebase (Phase A3 confirmed this); the only existing string->icon
// precedent is NavRail.tsx's local ICON_MAP, built from directly-imported
// lucide components in the same file — this follows that same convention
// rather than introducing a new shared lib file.
const SECTION_ICON_RULES: [RegExp, LucideIcon][] = [
  [/north star|success metric/i, Target],
  [/pestel/i, Globe],
  [/porter|five forces/i, Shield],
  [/jtbd|job to be done/i, CheckSquare],
  [/persona/i, User],
  [/journey/i, Map],
  [/risk|assumption/i, AlertTriangle],
  [/competitor|competitive/i, Swords],
  [/market/i, TrendingUp],
  [/architecture|system design/i, Boxes],
  [/requirement|user stor/i, ListChecks],
  [/metric|kpi/i, BarChart3],
  [/generated by/i, Bot],
];

function sectionIcon(label: string): LucideIcon {
  for (const [re, Icon] of SECTION_ICON_RULES) {
    if (re.test(label)) return Icon;
  }
  return FileText;
}

interface ArtifactTreeProps {
  artifacts: string[];
  currentStage: number;
  selected: string | null;
  activeSectionId: string | null;
  isStale: (file: string) => boolean;
  getVersion: (file: string) => number;
  onSelectArtifact: (file: string) => void;
  onSectionClick: (file: string, anchorId: string) => void;
  reducedMotion: boolean;
  // C3 — list (default) or 2-column grid
  workspaceView?: 'list' | 'grid';
}

export default function ArtifactTree({
  artifacts, currentStage, selected, activeSectionId,
  isStale, getVersion, onSelectArtifact, onSectionClick, reducedMotion,
  workspaceView = 'list',
}: ArtifactTreeProps) {
  const currentFile = useMemo(
    () => artifacts.find(a => stageNum(a) === currentStage) ?? null,
    [artifacts, currentStage],
  );

  // Auto-expanded: only the row containing the current stage, by default.
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set(currentFile ? [currentFile] : []));
  useEffect(() => {
    if (currentFile) setExpanded(prev => (prev.has(currentFile) ? prev : new Set(prev).add(currentFile)));
  }, [currentFile]);

  // Per-artifact section cache — parsed fresh from current content each time
  // an artifact is (re)expanded, never persisted across a content change.
  const [sectionsByFile, setSectionsByFile] = useState<Record<string, Section[]>>({});
  const [loadingFile, setLoadingFile] = useState<string | null>(null);
  const fetchTokenRef = useRef(0);

  const loadSections = useCallback((file: string) => {
    const token = ++fetchTokenRef.current;
    setLoadingFile(file);
    fetch(`/api/improve?file=${encodeURIComponent(file)}`)
      .then(r => r.json())
      .then(d => {
        if (token !== fetchTokenRef.current) return; // stale response, ignore
        const raw = d.content ?? '';
        const { content } = parseContentDetailed(raw);
        setSectionsByFile(prev => ({ ...prev, [file]: parseSections(content) }));
      })
      .catch(() => { if (token === fetchTokenRef.current) setSectionsByFile(prev => ({ ...prev, [file]: [] })); })
      .finally(() => { if (token === fetchTokenRef.current) setLoadingFile(null); });
  }, []);

  const toggleExpand = useCallback((file: string, state: RowState) => {
    if (state === 'pending') return; // no chevron — nothing to toggle
    setExpanded(prev => {
      const next = new Set(prev);
      if (next.has(file)) { next.delete(file); }
      else {
        next.add(file);
        if (!sectionsByFile[file]) loadSections(file);
      }
      return next;
    });
  }, [sectionsByFile, loadSections]);

  // If the current-stage row is auto-expanded on mount/stage-advance and its
  // sections haven't been loaded yet, load them once.
  useEffect(() => {
    if (currentFile && expanded.has(currentFile) && !sectionsByFile[currentFile] && loadingFile !== currentFile) {
      loadSections(currentFile);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentFile, expanded]);

  // Part 5 — feel, not just duration: reuse the product's own weighted
  // "entrances" cubic-bezier (lib/motion/primitives.ts's `easing.out`,
  // already piped through workspaceMotion) instead of the generic 'ease-out'
  // keyword. This is the decelerate-hard curve 21st.dev's tree view actually
  // uses under the hood — durations are unchanged (80/120ms).
  const cssEaseOut = `cubic-bezier(${workspaceMotion.easing.out.join(',')})`;
  const hoverT = reducedMotion ? 'none' : `background-color ${workspaceMotion.hoverMs}ms ${cssEaseOut}`;

  // Part 1 (Workspace Design Maturity Sprint) — the "STAGE X-Y" band
  // grouping from the previous sprint is REMOVED here. It read as a
  // synthetic taxonomy on top of a hierarchy that is actually flat:
  // Project -> Artifact (however many exist on disk, dynamic) -> Section
  // (parsed) -> Evidence (future, not built). No intermediate container.

  // C3 — Grid view: 2-column card layout. Same per-file data as list rows,
  // formatted as compact cards. Sections/chevrons are list-only.
  if (workspaceView === 'grid') {
    return (
      <div style={{ margin: '0 8px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4px' }}>
        {artifacts.map(file => {
          const state   = rowState(file, currentStage);
          const active  = selected === file;
          const col     = stageColor(file);
          const stale   = isStale(file);
          const ver     = getVersion(file);
          const isCurrent = state === 'current';
          const labelColor = state === 'pending'
            ? '#334155'
            : active ? col : stale ? '#f59e0b' : isCurrent ? '#e2e8f0' : '#64748b';

          return (
            <button
              key={file}
              onClick={() => onSelectArtifact(file)}
              style={{
                padding: '7px 8px', textAlign: 'left' as const,
                border: `1px solid ${active ? col : isCurrent ? `${col}44` : stale ? '#f59e0b33' : '#0a1a2e'}`,
                borderRadius: '5px', cursor: 'pointer',
                backgroundColor: active ? '#0a1509' : isCurrent ? '#081208' : 'transparent',
                fontFamily: "'JetBrains Mono','Fira Code',monospace",
                fontSize: '10px', color: labelColor,
                transition: hoverT,
                display: 'flex', flexDirection: 'column' as const, gap: '3px',
              }}
              onMouseEnter={e => { if (!active) (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(255,255,255,0.04)'; }}
              onMouseLeave={e => { if (!active) (e.currentTarget as HTMLButtonElement).style.backgroundColor = isCurrent ? '#081208' : 'transparent'; }}
            >
              <FileText size={10} color={state === 'pending' ? '#334155' : (stale ? '#f59e0b' : col)}
                fill={state === 'written' && !stale ? `${col}33` : 'none'}
                strokeWidth={isCurrent ? 2.25 : 1.5}
                style={{ flexShrink: 0 }}
              />
              <span style={{ lineHeight: 1.3, textTransform: 'capitalize' as const, wordBreak: 'break-word' as const }}>
                {humanName(file)}
              </span>
              <div style={{ display: 'flex', gap: '3px', alignItems: 'center', flexWrap: 'wrap' as const }}>
                {state !== 'pending' && ver > 0 && <span style={{ fontSize: '9px', color: '#4ade8066' }}>v{ver}</span>}
                {state === 'pending' && <span style={{ fontSize: '9px', color: '#334155' }}>v0</span>}
                {stale && <TriangleAlert size={8} color="#f59e0b88" />}
              </div>
            </button>
          );
        })}
      </div>
    );
  }

  return (
    <div style={{ margin: '0 8px' }}>
      <div style={{ display: 'flex', flexDirection: 'column' }}>
              {artifacts.map(file => {
                const state    = rowState(file, currentStage);
                const active   = selected === file;
                const col      = stageColor(file);
                const stale    = isStale(file);
                const ver      = getVersion(file);
                const isOpen   = expanded.has(file);
                const sections = sectionsByFile[file] ?? [];
                const isLoadingSections = loadingFile === file;
                const isCurrent = state === 'current';

                // Baseline tiering (artifact row dimmer than an active/current
                // row, brighter than a section row) — `current` overrides it.
                const labelColor = state === 'pending'
                  ? '#334155'
                  : active ? col : stale ? '#f59e0b' : isCurrent ? '#e2e8f0' : '#64748b';

                return (
                  <div key={file} style={{ marginBottom: 'var(--ig-space-1)' }}>
                    <div
                      // C4 — ig-interactive-row: 80ms ease-out hover, same treatment as CSS class.
                      // Inline handlers override the class for active/current state specificity.
                      className="ig-interactive-row"
                      style={{
                        display: 'flex', alignItems: 'center', gap: '4px',
                        // C3 — the current-stage row keeps its accent bar and
                        // tint even when not the selected artifact, so it
                        // reads as "you are here" independent of selection.
                        borderLeft: `${isCurrent ? 3 : 2}px solid ${active ? col : isCurrent ? col : stale ? '#f59e0b33' : 'transparent'}`,
                        backgroundColor: active ? '#0a1509' : isCurrent ? '#081208' : 'transparent',
                        transition: hoverT,
                        borderRadius: 0, // artifact rows stay flush — accent bar must not be clipped
                      }}
                      onMouseEnter={e => { if (!active) (e.currentTarget as HTMLDivElement).style.backgroundColor = 'rgba(255,255,255,0.04)'; }}
                      onMouseLeave={e => { if (!active) (e.currentTarget as HTMLDivElement).style.backgroundColor = isCurrent ? '#081208' : 'transparent'; }}
                    >
                      {/* Chevron — Written/Current only, per W1. I4: lucide
                          ChevronRight rotated via framer-motion, 120ms. */}
                      <button
                        onClick={() => toggleExpand(file, state)}
                        aria-label={state === 'pending' ? undefined : (isOpen ? `Collapse ${humanName(file)}` : `Expand ${humanName(file)}`)}
                        aria-hidden={state === 'pending'}
                        tabIndex={state === 'pending' ? -1 : 0}
                        style={{
                          width: '16px', flexShrink: 0, background: 'none', border: 'none', cursor: state === 'pending' ? 'default' : 'pointer',
                          color: '#334155', padding: '7px 0 7px 8px',
                          visibility: state === 'pending' ? 'hidden' : 'visible',
                          display: 'flex', alignItems: 'center',
                        }}
                      >
                        <motion.span
                          style={{ display: 'flex' }}
                          animate={{ rotate: isOpen ? 90 : 0 }}
                          transition={{ duration: reducedMotion ? 0 : workspaceMotion.expandCollapseMs / 1000, ease: workspaceMotion.easing.out }}
                        >
                          <ChevronRight size={12} />
                        </motion.span>
                      </button>

                      <button
                        onClick={() => onSelectArtifact(file)}
                        style={{
                          flex: 1, padding: '7px 12px 7px 0', textAlign: 'left', cursor: 'pointer', border: 'none',
                          fontFamily: "'JetBrains Mono','Fira Code',monospace", fontSize: 'var(--ig-t-caption-size)',
                          fontWeight: isCurrent ? 700 : 500,
                          backgroundColor: 'transparent', color: labelColor,
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                          {/* I2: FileText carries the three-state treatment
                              directly — filled (written), bold ring stroke
                              (current), dim hollow stroke (pending). */}
                          <FileText
                            size={12}
                            style={{ flexShrink: 0 }}
                            color={state === 'pending' ? '#334155' : (stale ? '#f59e0b' : col)}
                            fill={state === 'written' && !stale ? (ver > 0 ? '#4ade8033' : `${col}33`) : 'none'}
                            strokeWidth={isCurrent ? 2.25 : 1.5}
                          />
                          <span style={{ lineHeight: 1.4, textTransform: 'capitalize' as const }}>{humanName(file)}</span>
                          {state !== 'pending' && ver > 0 && <span style={{ fontSize: '11px', color: '#4ade8066' }}>v{ver}</span>}
                          {state === 'pending' && <span style={{ fontSize: '11px', color: '#334155' }}>v0</span>}
                          {stale && <TriangleAlert size={9} color="#f59e0b88" style={{ flexShrink: 0 }} />}
                        </div>
                      </button>
                    </div>

                    {/* Sections — parsed fresh per expand, zero rows for pending is correct.
                        Part 3/5: AnimatePresence height+opacity+subtle scale-in, 120ms,
                        reusing workspaceMotion.easing.out (the product's "entrances"
                        cubic-bezier) instead of the generic 'easeOut' keyword — same
                        decelerate-hard weight 21st.dev's tree view uses, duration unchanged. */}
                    <AnimatePresence initial={false}>
                    {state !== 'pending' && isOpen && (
                      <motion.div
                        initial={reducedMotion ? false : { height: 0, opacity: 0, scale: 0.98 }}
                        animate={{ height: 'auto', opacity: 1, scale: 1 }}
                        exit={reducedMotion ? undefined : { height: 0, opacity: 0, scale: 0.98 }}
                        transition={{ duration: reducedMotion ? 0 : workspaceMotion.expandCollapseMs / 1000, ease: workspaceMotion.easing.out }}
                        style={{ overflow: 'hidden', transformOrigin: 'top' }}
                      >
                      <div style={{ paddingLeft: '30px', display: 'flex', flexDirection: 'column' }}>
                        {isLoadingSections && (
                          <div style={{ fontSize: '11px', color: '#1e293b', padding: '4px 8px' }}>Loading sections…</div>
                        )}
                        {!isLoadingSections && sections.length === 0 && (
                          <div style={{ fontSize: '11px', color: '#1e293b', padding: '4px 8px' }}>No sections</div>
                        )}
                        {!isLoadingSections && sections.map(s => {
                          const isActiveSection = active && activeSectionId === s.anchorId;
                          const SectionIcon = sectionIcon(s.label);
                          return (
                            <button
                              key={s.anchorId}
                              onClick={() => onSectionClick(file, s.anchorId)}
                              className="ig-interactive-row"
                              style={{
                                display: 'flex', alignItems: 'center', gap: '6px',
                                textAlign: 'left', border: 'none', cursor: 'pointer',
                                fontFamily: "'JetBrains Mono','Fira Code',monospace", fontSize: '11px',
                                padding: '4px 8px', borderRadius: '3px', marginBottom: '1px',
                                // Dimmer baseline than artifact rows; the
                                // active-section highlight is a "you are
                                // here" state and is allowed to exceed it.
                                color: isActiveSection ? '#e2e8f0' : '#3f4c5e',
                                backgroundColor: isActiveSection ? '#0d1a10' : 'transparent',
                                borderLeft: `2px solid ${isActiveSection ? col : 'transparent'}`,
                                // Part 3 — same 80ms hover transition as
                                // artifact rows, no exceptions by position.
                                // Previously section rows had zero hover
                                // feedback (Phase A1 finding).
                                transition: hoverT,
                              }}
                              onMouseEnter={e => { if (!isActiveSection) (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'rgba(255,255,255,0.04)'; }}
                              onMouseLeave={e => { if (!isActiveSection) (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'transparent'; }}
                            >
                              {/* Part 2 D3 — keyword-matched section icon,
                                  smaller and dimmer than the artifact row's
                                  FileText so it stays visually subordinate. */}
                              <SectionIcon size={10} strokeWidth={1.5} style={{ flexShrink: 0 }} color={isActiveSection ? col : '#3f4c5e'} />
                              <span>{s.label}</span>
                            </button>
                          );
                        })}
                      </div>
                      </motion.div>
                    )}
                    </AnimatePresence>
                  </div>
                );
      })}
      </div>
    </div>
  );
}
