// src/app/api/journey-state/route.ts
// Mission 14 Phase 2 Stage B — new, additive, read-only endpoint.
// Does NOT modify /api/data/route.ts, which stays exactly as it is today.
//
// Run-resolution (getLatestProject) is intentionally duplicated from
// /api/data/route.ts rather than extracted into a shared module, because
// that file is explicitly out of scope for this change. Same algorithm,
// not reinvented.
//
// DATA SOURCE NOTE: journey.json's decisions[] does NOT contain agent
// attribution despite coordinator-v2.js passing `agentExecution` into
// journey.addDecision() — JourneyEngine.addDecision() normalizes to a
// fixed field whitelist that drops it before the state is ever saved to
// disk (verified by reading journey-engine.js and a real journey.json).
// The only place agent attribution actually reaches disk is the artifact
// markdown file itself, under a "## Generated By" heading written by
// persistArtifacts() — already filtered to successful agents only. This
// route derives agentsByStage from that heading via each stage's
// outputFile, not from decisions[].

import { NextResponse } from 'next/server';
import fs               from 'fs';
import path             from 'path';

const BASE_PATH = process.env.PROJECT_PATH ?? '';

function getLatestProject(): string | null {
  if (!BASE_PATH) return null;
  try {
    const dirs = fs.readdirSync(BASE_PATH)
      .filter(n =>
        !n.startsWith('.') &&
        fs.statSync(path.join(BASE_PATH, n)).isDirectory()
      )
      .sort((a, b) => {
        const ta = parseInt(a.split('-').pop() ?? '0', 10);
        const tb = parseInt(b.split('-').pop() ?? '0', 10);
        return tb - ta; // descending — newest first
      });
    return dirs.length ? dirs[0] : null;
  } catch { return null; }
}

interface JourneyStageOut {
  summary?:     string;
  decision?:    string;
  reasoning?:   string;
  confidence?:  string;
  conflicts?:   string;
  startedAt?:   string;
  completedAt?: string;
  durationMs?:  number;
  outputFile?:  string;
  artifacts?:   string[];
}

// Parses the "## Generated By" list written by persistArtifacts() in
// coordinator-v2.js. Returns the list verbatim (including the
// "Coordinator (direct merge)" fallback line when no agent succeeded) —
// that IS the ground-truth "successful agents" computation already applied
// at write time; this route does not re-filter it.
function parseGeneratedBy(content: string): string[] {
  const marker = '## Generated By';
  const idx = content.indexOf(marker);
  if (idx === -1) return [];
  const after = content.slice(idx + marker.length);
  const end = after.indexOf('\n---');
  const block = end === -1 ? after : after.slice(0, end);
  return block
    .split('\n')
    .map(l => l.trim())
    .filter(l => l.startsWith('- '))
    .map(l => l.slice(2).trim())
    .filter(Boolean);
}

export async function GET() {
  if (!BASE_PATH) {
    return NextResponse.json(
      { error: 'PROJECT_PATH not set', currentStage: 0, stages: {}, agentsByStage: {} },
      { status: 500 }
    );
  }

  const project = getLatestProject();
  if (!project) {
    return NextResponse.json({ currentStage: 0, stages: {}, agentsByStage: {} });
  }

  const projectPath = path.join(BASE_PATH, project);
  const journeyPath = path.join(projectPath, 'journey.json');

  let journey: { currentStage?: string | number; stages?: Record<string, any> };
  try {
    journey = JSON.parse(fs.readFileSync(journeyPath, 'utf-8'));
  } catch {
    return NextResponse.json({ currentStage: 0, stages: {}, agentsByStage: {} });
  }

  const currentStage = parseInt(String(journey.currentStage ?? '0'), 10) || 0;
  const rawStages = journey.stages ?? {};

  const stages:        Record<string, JourneyStageOut> = {};
  const agentsByStage: Record<string, string[]>         = {};

  for (const [stageId, data] of Object.entries<any>(rawStages)) {
    // Deliberately omit `output` and `history` — output is large and
    // already available via /api/data?file=X; no consumer needs it
    // duplicated here.
    stages[stageId] = {
      summary:     data.summary,
      decision:    data.decision,
      reasoning:   data.reasoning,
      confidence:  data.confidence,
      conflicts:   data.conflicts,
      startedAt:   data.startedAt,
      completedAt: data.completedAt,
      durationMs:  data.durationMs,
      outputFile:  data.outputFile,
      artifacts:   data.artifacts,
    };

    if (data.outputFile) {
      try {
        // outputFile is already project-relative, e.g. "artifacts/0-idea-intake.md"
        const artifactPath = path.join(projectPath, data.outputFile);
        const content = fs.readFileSync(artifactPath, 'utf-8');
        agentsByStage[stageId] = parseGeneratedBy(content);
      } catch {
        agentsByStage[stageId] = [];
      }
    } else {
      agentsByStage[stageId] = [];
    }
  }

  return NextResponse.json({ currentStage, stages, agentsByStage });
}
