// Mission Control v1 — Batch M1 — Orchestration adapter.
//
// LAYERING LAW (non-negotiable):
//   Runtime API → Execution Store → [THIS ADAPTER] → Viz Models → Components
//
// This is the ONLY file permitted to know runtime concepts — `agentsByStage`,
// `Generated By` class names, `completedAt`, journey stage indices. Everything
// it emits is presentation-only: a node has a `status`, never a `completedAt`.
// If a viz component prop ever reads a runtime field, the layering has leaked.
//
// Pure function. No React, no fetch, no store import. Unit-testable in isolation.
//
// Agent state is DERIVED, not read: the store's `agents` map is keyed by stage
// (`agentsByStage`), not by agent (verified M0). Per-agent status is computed
// from AGENT_DEFS.stages[] ownership + each stage's completion — the id-based
// primary signal. The runtime's `Generated By` class names are a secondary
// reinforcement only, mapped through CLASSNAME_TO_ID.

import type { Node, Edge } from '@xyflow/react';
import type { StageState, AgentState, MetricSnapshot } from '../types';

// ── Public presentation vocabulary ───────────────────────────────────────────

export type AgentId = 'CO' | 'PS' | 'RE' | 'UX' | 'AR' | 'QA';
export type AgentStatus = 'active' | 'done' | 'waiting';
export type RunState = 'empty' | 'running' | 'complete';
export type StageStatus = 'done' | 'current' | 'low-confidence' | 'pending';
export type EdgeVariant = 'active' | 'waiting' | 'blocked';

// Injected by the caller (office/page.tsx passes AGENT_DEFS in M3). The adapter
// imports NOTHING from office/ — dependency injection avoids a circular import.
export interface AgentDef {
  id: string;
  name: string;
  fullName: string;
  color: string;
  stages: readonly number[];
  zone: string;
  role: string;
  isCoordinator: boolean;
}

// `type` (not interface) so the shapes satisfy XYFlow v12's
// `Record<string, unknown>` node-data constraint.
export type AgentNodeData = {
  agentId: AgentId;
  label: string;
  color: string;            // Foundation token, e.g. 'var(--ig-agent-ps)'
  status: AgentStatus;
  isCoordinator: boolean;
};

export type FlowEdgeData = {
  variant: EdgeVariant;
};

export interface StageNode {
  index: number;
  label: string;
  status: StageStatus;
}

// Node CENTRE positions, injected (see src/components/viz/layout.ts). Layout is
// a design decision, not a data derivation — kept out of the adapter so it can
// be hand-tuned without touching derivation logic.
export type AgentLayout = Record<AgentId, { x: number; y: number }>;

export interface OrchestrationModel {
  nodes: Node<AgentNodeData>[];
  edges: Edge<FlowEdgeData>[];
  stageNodes: StageNode[];
  activeAgentId: AgentId | null;  // the single alive node (specialist OR CO)
  coordinatorActive: boolean;     // convenience: activeAgentId === 'CO'
  runState: RunState;
}

// The data-bearing subset of the execution store the adapter reads. Declared
// locally (not imported from store.ts) to keep this file free of any store or
// React dependency — anything with this shape can drive it.
export interface ExecutionState {
  currentStage: number;
  stages: Record<string, StageState>;
  agents: Record<string, AgentState[]>;   // keyed by stage id — see M0
  metrics: MetricSnapshot | null;
}

// ── Runtime-only knowledge (stays inside this layer) ──────────────────────────

// `Generated By` headings emit agent CLASS names, not the short ids used
// everywhere else. CodeAgent is a real runtime contributor (stages 11/12/14)
// but is NOT one of the six graph roles → maps to null, surfaced later in the
// ActivityStream, never as a node.
const CLASSNAME_TO_ID: Record<string, AgentId | null> = {
  'Coordinator (direct merge)': 'CO',
  Coordinator: 'CO',
  ProductStrategyAgent: 'PS',
  ResearchAgent: 'RE',
  UXAgent: 'UX',
  ArchitectAgent: 'AR',
  QAAgent: 'QA',
  CodeAgent: null,
};

// Canonical 15-stage lifecycle labels (0–14). Domain data the adapter layer
// legitimately owns; mirrors STAGE_LABEL in office/page.tsx. There are 15
// stages even though metrics.totalStages reports 14 — never size the rail from
// metrics.
const STAGE_LABELS = [
  'Idea Intake', 'Discovery', 'Problem Definition', 'Solution Design',
  'MVP Hypothesis', 'Validation', 'Prioritization', 'PRD',
  'UX Design', 'Usability', 'Architecture', 'Backlog & Release',
  'Implementation', 'QA & Readiness', 'Prototype Prompt',
] as const;
const STAGE_COUNT = STAGE_LABELS.length; // 15

const AGENT_TOKEN: Record<AgentId, string> = {
  CO: 'var(--ig-agent-co)',
  PS: 'var(--ig-agent-ps)',
  RE: 'var(--ig-agent-re)',
  UX: 'var(--ig-agent-ux)',
  AR: 'var(--ig-agent-ar)',
  QA: 'var(--ig-agent-qa)',
};

// If the store hasn't been touched in this long, an in-progress-looking stage
// is a stale artifact of an abandoned run, not live work — motion must stop.
const STALE_AFTER_MS = 120_000; // 2 minutes

// ── Geometry ──────────────────────────────────────────────────────────────
// Positions are injected (AgentLayout), never computed here. The adapter only
// converts an injected visual CENTRE to the top-left corner XYFlow positions by.

const CO_SIZE = 80;
const SPECIALIST_SIZE = 56;

function topLeft(center: { x: number; y: number }, size: number) {
  return { x: center.x - size / 2, y: center.y - size / 2 };
}

// ── Run-state derivation (spec correction C2) ─────────────────────────────────

function deriveRunState(execution: ExecutionState): RunState {
  const stageList = Object.values(execution.stages);
  const anyStarted = stageList.some((s) => Boolean(s.startedAt));
  if (!anyStarted) return 'empty';

  const inProgress = stageList.some((s) => s.startedAt && !s.completedAt);
  const lastUpdated = execution.metrics?.lastUpdated;
  const isStale = lastUpdated
    ? Date.now() - Date.parse(lastUpdated) > STALE_AFTER_MS
    : false;

  // A stale mid-run counts as not-running so nothing breathes forever (e.g. AR,
  // owner of stage 14, after the process exits).
  return inProgress && !isStale ? 'running' : 'complete';
}

// ── Agent status derivation (spec corrections C1 + C5) ────────────────────────

function deriveActiveAgentId(
  execution: ExecutionState,
  agentDefs: readonly AgentDef[],
  runState: RunState,
): AgentId | null {
  if (runState !== 'running') return null;
  // Exactly one agent owns any given stage (STAGE_AGENT is 1:1). The owner of
  // currentStage is the single alive node — specialist OR Coordinator.
  const owner = agentDefs.find((d) => d.stages.includes(execution.currentStage));
  return owner ? (owner.id as AgentId) : null;
}

function deriveDoneIds(
  execution: ExecutionState,
  agentDefs: readonly AgentDef[],
): Set<AgentId> {
  const done = new Set<AgentId>();

  // Primary, id-based signal: an agent is done if it owns ≥1 completed stage.
  for (const def of agentDefs) {
    if (def.stages.some((idx) => execution.stages[String(idx)]?.completedAt)) {
      done.add(def.id as AgentId);
    }
  }

  // Secondary reinforcement: `Generated By` class names on completed stages.
  for (const [stageId, stage] of Object.entries(execution.stages)) {
    if (!stage.completedAt) continue;
    for (const agent of execution.agents[stageId] ?? []) {
      const id = CLASSNAME_TO_ID[agent.id];
      if (id) done.add(id);
    }
  }

  return done;
}

function statusFor(
  id: AgentId,
  activeAgentId: AgentId | null,
  doneIds: Set<AgentId>,
): AgentStatus {
  if (id === activeAgentId) return 'active';
  if (doneIds.has(id)) return 'done';
  return 'waiting';
}

// ── Stage-rail derivation (spec §5 rule 6, corrections C4) ────────────────────

function deriveStageNodes(execution: ExecutionState, runState: RunState): StageNode[] {
  const nodes: StageNode[] = [];
  for (let i = 0; i < STAGE_COUNT; i++) {
    const stage = execution.stages[String(i)];
    let status: StageStatus;
    if (runState === 'running' && i === execution.currentStage && !stage?.completedAt) {
      status = 'current';
    } else if (stage?.completedAt && stage.confidence === 'low') {
      status = 'low-confidence'; // amber overrides done
    } else if (stage?.completedAt) {
      status = 'done';
    } else {
      status = 'pending';
    }
    nodes.push({ index: i, label: STAGE_LABELS[i], status });
  }
  return nodes;
}

// ── Public entry point ────────────────────────────────────────────────────────

export function toOrchestrationModel(
  execution: ExecutionState,
  agentDefs: readonly AgentDef[],
  layout: AgentLayout,
): OrchestrationModel {
  const runState = deriveRunState(execution);
  const activeAgentId = deriveActiveAgentId(execution, agentDefs, runState);
  const doneIds = deriveDoneIds(execution, agentDefs);

  const coordinator = agentDefs.find((d) => d.isCoordinator);
  const specialists = agentDefs.filter((d) => !d.isCoordinator);

  const nodes: Node<AgentNodeData>[] = [];

  if (coordinator) {
    const id = coordinator.id as AgentId;
    nodes.push({
      id,
      type: 'coordinator',
      position: topLeft(layout[id], CO_SIZE),
      data: {
        agentId: id,
        label: coordinator.name,
        color: AGENT_TOKEN[id],
        status: statusFor(id, activeAgentId, doneIds),
        isCoordinator: true,
      },
    });
  }

  specialists.forEach((def) => {
    const id = def.id as AgentId;
    nodes.push({
      id,
      type: 'agent',
      position: topLeft(layout[id], SPECIALIST_SIZE),
      data: {
        agentId: id,
        label: def.name,
        color: AGENT_TOKEN[id],
        status: statusFor(id, activeAgentId, doneIds),
        isCoordinator: false,
      },
    });
  });

  // CO → each specialist. The active edge is the one to the alive specialist,
  // and only while running. When CO itself is active nothing is handed off, so
  // no edge animates (correction C1).
  const edges: Edge<FlowEdgeData>[] = coordinator
    ? specialists.map((def) => {
        const isActive =
          runState === 'running' &&
          activeAgentId !== null &&
          activeAgentId !== coordinator.id &&
          def.id === activeAgentId;
        return {
          id: `${coordinator.id}-${def.id}`,
          source: coordinator.id,
          target: def.id,
          type: 'flow',
          data: { variant: isActive ? 'active' : 'waiting' },
        };
      })
    : [];

  return {
    nodes,
    edges,
    stageNodes: deriveStageNodes(execution, runState),
    activeAgentId,
    coordinatorActive: activeAgentId === 'CO',
    runState,
  };
}
