import fs from 'fs/promises';
import path from 'path';
import { existsSync } from 'fs';

export class FileManager {
  constructor(baseDir) {
    this.baseDir = baseDir;
  }

  /**
   * Create standard project structure
   */
  async createProjectStructure(projectName) {
    const projectDir = path.join(this.baseDir, projectName);

    const dirs = [
      projectDir,
      path.join(projectDir, 'product'),
      path.join(projectDir, 'docs'),
      path.join(projectDir, 'ui'),
      path.join(projectDir, 'backend'),
      path.join(projectDir, 'frontend'),
      path.join(projectDir, 'logs')
    ];

    for (const dir of dirs) {
      await fs.mkdir(dir, { recursive: true });
    }

    // Create initial README
    const readme = this.generateReadme(projectName);
    await this.saveFile(path.join(projectDir, 'README.md'), readme);

    return projectDir;
  }

  /**
   * Save text file
   */
  async saveFile(filePath, content) {
    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(filePath, content, 'utf-8');
    return filePath;
  }

  /**
   * Save JSON file
   */
  async saveJSON(filePath, data) {
    const content = JSON.stringify(data, null, 2);
    return this.saveFile(filePath, content);
  }

  /**
   * Read file
   */
  async readFile(filePath) {
    return fs.readFile(filePath, 'utf-8');
  }

  /**
   * Read JSON file
   */
  async readJSON(filePath) {
    const content = await this.readFile(filePath);
    return JSON.parse(content);
  }

  /**
   * Check if file exists
   */
  exists(filePath) {
    return existsSync(filePath);
  }

  /**
   * Generate initial README
   */
  generateReadme(projectName) {
    const title = projectName
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');

    return `# ${title}

> Generated by Product Builder Coworker

## Project Structure

\`\`\`
├── product/          # Product documentation
│   ├── brief.md     # Product brief
│   └── prd.md       # Product Requirements Document
├── docs/            # Technical documentation
├── ui/              # UI/UX artifacts
├── backend/         # Backend code
├── frontend/        # Frontend code
└── logs/            # Build logs
\`\`\`

## Status

- [x] Phase 1: Product Discovery & Specification
- [ ] Phase 2: Task Decomposition & Architecture
- [ ] Phase 3: Code Generation
- [ ] Phase 4: Deployment

## Getting Started

\`\`\`bash
# Review the product documentation
cat product/brief.md
cat product/prd.md

# Continue to next phase
pbc continue
\`\`\`

---

*Generated on ${new Date().toISOString()}*
`;
  }

  /**
   * Append to log file
   */
  async appendLog(projectDir, message) {
    const logPath = path.join(projectDir, 'logs', 'build.log');
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] ${message}\n`;
    await fs.appendFile(logPath, logEntry, 'utf-8');
  }
}
